# This file was generated by GoReleaser. DO NOT EDIT.
cask "bespoke" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "c87ee478faa4de4b0673b6615f1ef11313b3c1e4bdc8899c63ab54497a60fee3"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
    on_arm do
      sha256 "84aa82bdf47053916a40c6613489864120e0d2cb19a6b72c77c080050260a0cc"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
  end

  on_linux do
    on_intel do
      sha256 "0aed35c47e1974c4e30ab668a991685776529f19bb89ff20746b3f6ef2968a66"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
    on_arm do
      sha256 "118e9ca2c679a8f705ec5118484d4d79340ede534865c967ac1f6767f679c362"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
  end

  name "bespoke"
  desc "A personal platform for one-off, just-for-me apps"
  homepage "https://github.com/bketelsen/bespoke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bespoke"

  # No zap stanza required

end
