# This file was generated by GoReleaser. DO NOT EDIT.
cask "bespoke" do
  version "0.13.0"

  on_macos do
    on_intel do
      sha256 "ec5eb48f9a97b18bde97773659b034635bb9e2ee5cb71b19643f4618feb10fe8"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
    on_arm do
      sha256 "670fe4002875573470369c8991f49707bb3a26513c7cf2c17ad29961c30bc64a"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b095c92cc97addcca7e4e0278814953324fbc00bfd06fc3e2e1cc93c589c94c"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
    on_arm do
      sha256 "204716e85e53fcdd8c4bd90869fcb517f00b145dead69d05d9ddf99fee170734"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
  end

  name "bespoke"
  desc "A personal platform for one-off, just-for-me apps"
  homepage "https://github.com/bketelsen/bespoke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bespoke"

  # No zap stanza required

end
