# This file was generated by GoReleaser. DO NOT EDIT.
cask "bespoke" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c98e797436714427461f3a08f2c656320ec6e2ce6497453eb4e532e03af11331"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
    on_arm do
      sha256 "a0982efa2cfcc96cd664f15c400d56eeb14cd36cbc1e42637f5082f8675d67d9"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e693968f6d3259f7661783d623566e09419e7bd5afcc5dd46cf95f20a654d843"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
    on_arm do
      sha256 "2bd1da8c6751b27dc1eb36b0f6ba4061772b0223c1b6b1e189170c1edfc3c9f2"
      url "https://github.com/bketelsen/bespoke/releases/download/v#{version}/bespoke_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bketelsen/bespoke/"
    end
  end

  name "bespoke"
  desc "A personal platform for one-off, just-for-me apps"
  homepage "https://github.com/bketelsen/bespoke"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bespoke"

  # No zap stanza required

end
