# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mwb < Formula
  desc "Mouse Without Borders client for Linux and macOS"
  homepage "https://github.com/bketelsen/mwb"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bketelsen/mwb/releases/download/v0.2.4/mwb_0.2.4_darwin_arm64.tar.gz"
      sha256 "674539cc4f0b6e0a8bef8b6c2049e0d3742d208c16aa52fd48e90c916a865a40"

      define_method(:install) do
        bin.install "mwb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bketelsen/mwb/releases/download/v0.2.4/mwb_0.2.4_linux_amd64.tar.gz"
      sha256 "6366576cc66f165c05f2e68554cc082af56df54ab7e7068bc96ce46e63b64de6"
      define_method(:install) do
        bin.install "mwb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bketelsen/mwb/releases/download/v0.2.4/mwb_0.2.4_linux_arm64.tar.gz"
      sha256 "8bbaacb4cc908e59a9076deb70bda8358f9b645b9a79bcc6c16f9105d0f3dafd"
      define_method(:install) do
        bin.install "mwb"
      end
    end
  end

  def caveats
    <<~EOS
      On macOS, grant Accessibility permissions before starting:
        System Settings > Privacy & Security > Accessibility > Add mwb

      On Linux, set up uinput access:
        sudo modprobe uinput
        echo 'KERNEL=="uinput", GROUP="input", MODE="0660"' | \
          sudo tee /etc/udev/rules.d/99-uinput.rules
        sudo udevadm control --reload-rules && sudo udevadm trigger
        sudo usermod -aG input $USER
    EOS
  end

  service do
    run opt_bin/"mwb"
    keep_alive true
    log_path var/"log/mwb.log"
    error_log_path var/"log/mwb.log"
  end
end
